#!/bin/bash

if ! [ -t 0 ]; then
	read -a ref
fi


IFS='/' read -ra REF <<< "${ref[2]}"
branch="${REF[2]}"

if [ $branch == "master" ]; then
	crumb=$(curl -u "admin:password" -s 'http://jenkins:8080/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,":",//crumb)')
	curl -u "admin:password" -H "$crumb" -X POST http://jenkins:8080/job/timeoff-management-application-job/buildWithParameters?delay=0sec&NODE_APP_PORT=3000&APP_CONTAINER_NAME=timeoff-mngmt-app
	
    if [ $? -eq 0 ]; then
		echo "*** Ok"
	else
		echo "*** Error"
	fi

fi